add some simple pattern checkers
- check if system includes (those not ending in .h or .hpp) are in angle brackets <>
- check if local includes (those ending in .h or .hpp) are in quotes ""
- check if QDebug is not included (use logging.h instead)
- check if size_t is fully qualified (std::size_t)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -45,8 +45,8 @@ jobs:
           travis_terminate 1
         fi
       fi
-      if ! build-scrips/check-size_t.sh; then
-        echo "size_t check failed."
+      if ! build-scrips/check-bad-patterns.sh; then
+        echo "Bad pattern detected. Check failed."
         travis_terminate 1
       fi
     before_deploy: skip
