CI: verify that there is no size_t (only std::size_t)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -45,6 +45,10 @@ jobs:
           travis_terminate 1
         fi
       fi
+      if ! build-scrips/check-size_t.sh; then
+        echo "size_t check failed."
+        travis_terminate 1
+      fi
     before_deploy: skip
     deploy:
       provider: script
