re-prioritize jobs
build static checker focal build first.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -22,6 +22,47 @@ jobs:
   include:
   - stage: build
     os: linux
+    dist: focal
+    name: Static Checks
+    addons:
+      apt:
+        update: true
+        packages:
+        - clang
+    install:
+    - sudo apt-get install -y clang-format-10 clazy clang-tidy-10
+    before_script:
+    - clang-format --version
+    - ln -s /usr/bin/clang-format-10 clang-format
+    - |
+      if ! PATH=$(pwd):$PATH build-scripts/format.sh check; then
+        echo "Format check failed."
+        echo "Use `build-scripts/format.sh apply` to auto-format the code."
+        travis_terminate 1
+      fi
+    script:
+    - cmake -GNinja
+            -DCMAKE_BUILD_TYPE=Release
+            -DQT_QM_PATH="$QT_QM_PATH"
+            -DCMAKE_PREFIX_PATH="$QT_PREFIX"
+            -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
+            -DCMAKE_C_COMPILER=${C_COMPILER}
+            -DSYSTEM_SUFFIX="-$TRAVIS_DIST"
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+            -S .
+            -B build
+    - cmake --build build --target install
+    after_success:
+    - ln -s /usr/bin/clang-tidy-10 clang-tidy
+      files=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
+      if ! PATH="$(pwd):$PATH" build-scripts/static-checks.py \
+           --compile-commands build/compile_commands.json \
+           --files $files --modes clang-tidy clazy
+      then
+        travis_terminate 2
+      fi
+  - stage: build
+    os: linux
     dist: xenial
     name: Build on Ubuntu Xenial
     before_install:
@@ -106,47 +147,6 @@ jobs:
     - export QT_PREFIX=""
     - export QT_QM_PATH="/usr/share/qt5/translations/"
     - export cmake="cmake"
-  - stage: build
-    os: linux
-    dist: focal
-    name: Static Checks
-    addons:
-      apt:
-        update: true
-        packages:
-        - clang
-    install:
-    - sudo apt-get install -y clang-format-10 clazy clang-tidy-10
-    before_script:
-    - clang-format --version
-    - ln -s /usr/bin/clang-format-10 clang-format
-    - |
-      if ! PATH=$(pwd):$PATH build-scripts/format.sh check; then
-        echo "Format check failed."
-        echo "Use `build-scripts/format.sh apply` to auto-format the code."
-        travis_terminate 1
-      fi
-    script:
-    - cmake -GNinja
-            -DCMAKE_BUILD_TYPE=Release
-            -DQT_QM_PATH="$QT_QM_PATH"
-            -DCMAKE_PREFIX_PATH="$QT_PREFIX"
-            -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
-            -DCMAKE_C_COMPILER=${C_COMPILER}
-            -DSYSTEM_SUFFIX="-$TRAVIS_DIST"
-            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-            -S .
-            -B build
-    - cmake --build build --target install
-    after_success:
-    - ln -s /usr/bin/clang-tidy-10 clang-tidy
-      files=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
-      if ! PATH="$(pwd):$PATH" build-scripts/static-checks.py \
-           --compile-commands build/compile_commands.json \
-           --files $files --modes clang-tidy clazy
-      then
-        travis_terminate 2
-      fi
   - stage: build
     os: windows
     name: Build on Windows/MinGW64
